
DROP DATABASE customer_behaviour;

CREATE DATABASE customer_behavior;

use customer_behavior;

select * from customer
Limit 5;

#Q1. What is the total revenue generated by male vs. female customers?
SELECT gender , SUM(purchase_amount) AS revenue
from customer
group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id , purchase_amount
from customer 
where discount_applied = 'Yes' And purchase_amount >= (Select Avg(purchase_amount) from customer);

#Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased, round(avg(review_rating),2) As "Avg Product Rating"
From customer 
group by item_purchased
order by AVG(review_rating) desc
Limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
Select shipping_type , round(avg(purchase_amount), 2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type ;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status,
       count(customer_id) as total_customer,
       round(avg(purchase_amount) ,2) as avg_spend,
       round(sum(purchase_amount) ,2) as total_revenue
from customer 
group by subscription_status
order by total_revenue, avg_spend;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as(
Select customer_id, previous_purchases,
Case
    When previous_purchases = 1 Then 'New'
    When previous_purchases Between 2 And 10 Then 'Returning'
    Else 'Loyal'
    End As customer_segment
From customer)
select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

#Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
 







